name: TylerUtilsMod
main: com.tylerhyper.utils.mod.TylerUtilsMod
version: 1.5
commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug
  tum:
    description: Shows information about the TylerUtilsMod.
    usage: "Usage: /tum <version | help | about>"
  tylerutilsmod:
    description: Shows information about the TylerUtilsMod.
    usage: "Usage: /tylerutilsmod <version | help | about>"
  admin:
    description: Switches into admin mode.
  fuckconsole:
    description: Fucks the consoles brains out.
  admininfo:
    description: Apply for Super Admin.
    usage: /admininfo
  ai:
    description: Apply for Super Admin.
    usage: /ai
  blowjob:
    description: Give a player a blowjob.
    usage: "Usage: /blowjob <player>"
  blowup:
    description: Make the player blow up.
    usage: "Usage: /blowup <player>"
  brb:
    description: Busy atm.
    usage: "Usage: /brb [on/off]"
  ci:
    description: Clear your inventory
    usage: "Usage: /ci"
  clear:
    description: Clear your inventory
    usage: "Usage: /clear"
  clearall:
    description: Clean all supered IPs of all admins
    usage: "Usage: /clearall"
  destroy:
    description: Destroy a player
    usage: "/destroy <player>"
  pussy:
    description: Fuck her right in da pussy
    usage: "/pussy <player>"
  destroypussy:
    description: Fuck her right in da pussy
    usage: "/destroypussy <player>"
  opitems:
    description: Gives the player op items.
    usage: "/opitems"
  impl:
    description: Implies you don't know what you are doing.
    usage: "/impl"
  longshaft:
    description: Gives you a long, hard shaft.
    usage: "/longshaft"
  personal:
    description: Runs a personal command.
    usage: "/personal"
  psl:
    description: Runs a persoanl command.
    usage: "/psl"
  relogger:
    description: Forces senior admins to relog.
    usage: "/relogger"
  purple:
    description: Graces the world with purple
    usage: "/purple"
  pex:
    description: Base command for PermissionsEX.
    usage: "/pex"
  pervert:
    description: Gets rid of perverted freaks.
    usage: "/pervert <player>"
  question:
    description: Asks a question.
    usage: "/question <question>"
  removelagg:
    description: Remove all forms of client lagg.
    usage: "/removelagg"
  requestop:
    description: Requests op.
    usage: "/requestop"
  rollbackfailed:
    description: Fixes a rollback if it fails.
    usage: "/rollbackfailed <player>"
  sendtaw:
    description: Sends all admins to the admin world.
    usage: "/sendtaw"
  shutup:
    description: Makes the player shutup.
    usage: "/shutup <player>"
  telnet:
    description: Toggles telnet for all admins.
    usage: "/telnet [on/off]"
  whore:
    description: Calls the player a whore.
    usage: "/whore <player>"
  tylerfuck:
    description: Calls the player a whore.
    usage: "/<command> <player>"